### ISSUE TITLE
Config files for coefficients of formulas

### ISSUE THREAD

**Issue by Gollwu** [Gollwu/LoLManager#11]

**Comment by qr7hur** [comment]
In my book, that kind of things should be part of the database rather than "config files". 
DB => potentially more granularity / easy to maintain across devices / easy to share/edit... 
I also think these coefficients may vary depending on the player and his team management choices. Maybe I'm wrong.

**Comment by Gollwu** [comment]
Ok for the database. But for the coefficients, they are more static than that like "On a gank, is map awareness more or less important than the ganking stat of the jungler?" which is independant from the team

**Comment by Gollwu** [comment]
If it's in the database we can close the ticket for now :)
