### ISSUE TITLE
Front framework

### ISSUE THREAD

**Issue by Nhacsam** [Gollwu/LoLManager#42]
Because of we choose to use a rest api, it could be usefull to use a framework for the front; angular, ionic, famo.us, ...

As you want ... rest api is not definive

**Comment by qr7hur** [comment]
It's often a good idea to use a framework, the question is: which framework?
Do you mind clarifying why the use of a RESTful API should imply that of a framework though?

**Comment by fabienDaou** [comment]
+1

**Comment by Nhacsam** [comment]
How do you want to make more than one page ? When getting the data ?

**Comment by Gollwu** [comment]
How about JQuery? Still the most popular out there and I think most of us have already use it once. Anyway if you have recommendations (and I think you have) we would be pleased to try new technologies. The men with the most experience (understand having used several front frameworks) should choose I think :) (Nhacsam or Zigglick I guess)

**Comment by Nhacsam** [comment]
I only used jQuery and angular.
This is the answer of my two question which will choose the best framework, I think.

Think about 2 pages : the team page (where you can see your team and the players stats) and your profile page (where you can see/choose you email, your password, your pseudo, your sucess).

Do you really need two pages or everything can be in a same page ? (same page = jQuery)
Do you prefer to have 2 html page ? (If one html : angular, ionic, ...)
If yes, do prefer getting the data form the api server side or client side ? (if yes jQuery is goo too)
If server side, do we really need an API REST or can we use a template framework ? (I only know jade)

Whatever you choose, we can create as many file as we want for developping and compile its in on single file with Grunt or gulp.

For example, the project I'm working is done with angular. You download the javascript and the index.html only once and the page change without an other server request. But I have a big MVC architecture. All is compiled with gulp. The datas are retreive in a REST API. I can't give you the link again in a public repository (sorry).
Why we choose it ? We can put the html and the js in a mobile application (with Phonegap and Cordova).

**Comment by qr7hur** [comment]
[My avatar raises his hand]

Why not using a JavaScript framework designed for games? That would probably help us on the interactive map part, and they may well have suitable data structures for communication in games also ... 

If we plan to go multi-agent -and if I understand correctly what this is- it seems those "game engines" do most of the structural work for us.

If you know TodoMVC for javascript frameworks comparison, here is the equivalent for javascript game engines comparison (ie: same game build with various libs, code available to let you choose which one you like better): http://www.jsbreakouts.org/

At the first sight, examples created with those libraries do not really look like LoLManager, but I think they are worth checking out anyway!

PS: http://phaser.io/ has a cool site...

**Comment by Gollwu** [comment]
It seens to me that those frameworks designed for games do not fit our application, we do no need flash, fancy animations and shit from what I know. Correct me if I'm wrong. The only advantage would be the physics with the structure for multi agent but I think this is overkill as we don't really manage complicated things here.

For what Nhacsam said, I think we will have more than one page (There should be a lot of pages for the management system and one or two for the game engine). We could do only one page but I think it's a bit messy... I don't see the point sparing the server since we will do so much calls on the server anyway (so JQuery is ok?)

For Template vs Rest I think the main point is : Which one is better with all the calls we will need to do during one game to do some kind of real time between the two clients? I think it will be REST though :)

**Comment by Gollwu** [comment]
I got advised to use this library instead of a framework : https://facebook.github.io/react/

I'm checking this out

**Comment by Nhacsam** [comment]
React is a framework, I do not recommand it. You will need to learn new strange languages : JSX and CSSX. It's usefull if you want to make mobile app because you can compile it in a more native result. 

If you want 3D, I would like test [famous](http://famo.us/).

More than one page so. REST is not for the simulation. Simulation will be with web socket (for real time as you say). You have 3 solutions : 
- You compute your pages server side with a template engine and get complete pages. (jade)
- You make one request to get the views (html page) and an other AJAX request to get the model by the REST API. After, you fill your page client side with the result. (jQuery)
- You get all the html and js in the first page and you download only the model for each new page. (angular)

**Comment by fabienDaou** [comment]
Before reading your comments I would have opted for jQuery mainly because this is the only way I did things like these before.

Now between Jade and Angular, I prefer Angular just because it lets us build a REST API. Even though we can argue that it is not necessary atm I personally love having this kind of stand alone module. They can be useful for other projects and hey maybe we will need one later on for whatever reason.

_I VOTE Angular_

EDIT:
Afer thinking more, Jade might be enough too in our case

**Comment by Zigglick** [comment]
Mais comment je fais mon easter egg space invaders pour jouer à un vrai jeu si on prend pas un framework game engine?

**Comment by Gollwu** [comment]
Conclusion?

**Comment by fabienDaou** [comment]
SWIG
